version: 1
formatters:
  default:
    format: '%(asctime)s:%(name)s:%(module)s:%(funcName)s:%(lineno)d:%(levelname)s:%(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
  info:
    format: '%(levelname)s:%(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
  console:
    format: '%(asctime)s:%(funcName)s:%(lineno)d:%(levelname)s:%(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout
  main:
    () : __main__.logpath
    level: DEBUG
    formatter: default
  emaillog:
    () : __main__.email_logpath
    level: INFO
    formatter: info

loggers:
  mail_demultiplexing_results:
    level: DEBUG
    handlers: [console, main, emaillog]
    propagate: true
